### ISSUE TITLE
[公约]修订建议

### ISSUE THREAD

**Issue by kulocora** [green-android/green-android.github.io#1]
目前的版本侧重于 Dev 方面，那么我想以一个普通用户的身份提出修订建议。

必须：
*不强制请求任何权限[不给权限就退出]
*按需提出权限申请
*提供原生分享
*主动告知用户数据收集类型
*在旧版本可用的情况下不强制更新应用

建议：
*戴套
*将圆角矩形图标替换为方形
*部分或完整采用 Material Design 尤其是 icons

目前就想到这么多，感谢推动生态发展。

**Comment by kaiyangjia** [comment]
我想到关于推送的问题：
1. GCM在国内不可靠。
2. 国内的第三方推送SDK存在很严重的互相唤醒的问题

所以，我想可以建议开发者采用一种折中的策略，使用GCM和国内的混合推送。在GCM可用的时候就停止掉第三方的推送SDK，只用GCM，只有在必要的时候才启用第三方推送。此外，开发者还应该提供一个关闭推送的选项，让用户可以选择不使用推送。

**Comment by weiYz** [comment]
禁用权限还应包括：CALL_PHONE。如有需要拨打电话（非紧急），可用ACTION_DIAL代替，这样可以规避CALL_PHONE权限。

**Comment by oasisfeng** [comment]
『不强制请求任何权限』这一点可以考虑纳入下一版的公约中。

目前公约强调『可被验证性』这一原则，所以存在主观裁量的约束不适合纳入公约，纳入了也缺乏约束力。（比如『按需提出权限申请』，这个『按需』就有太大的主观解读空间）

另外，应用的设计和交互体验不是目前公约的侧重点，因为纳入这类约束会增加公约推行时的组织内部成本。比如原本研发团队可以自行或推动决定的，还要牵扯进UX团队，很多有意愿的开发团队就会望而却步了。

**Comment by oasisfeng** [comment]
@kaiyangjia GCM的接入成本较高（维持服务端与Google服务器的稳定连接），缺乏投入产出比的这一重要基础，很难推行。

**Comment by oasisfeng** [comment]
@weiYz 这个强制请求CALL_PHONE权限的情况普遍么？我之前还没有特别关注到。

**Comment by sunny9675** [comment]
关于第三方推送，在GCM无法入华的情况下首先集成各大厂家的推送服务：小米push，华为push，魅族push（打包集成sdk），尽量不要使用极光、百度云、个推等。另外听说今年三月泰尔实验室举行了安卓统一推送研讨会，也许在官方主持下，统一安卓推送服务，建立中国版的GCM是一个出路

**Comment by sunny9675** [comment]
另外，作为用户的角度，我们希望开发者可以适配安卓系统的新功能，并不仅仅是兼容。比如说安卓7.0的通知栏快捷回复，这个ios版微信已经支持很久了，然而安卓版微信仍然不支持，不知是否与target SDK version过低有关。

**Comment by oasisfeng** [comment]
@sunny9675 目前公约强调『可被验证性』这一原则，所以存在主观裁量的约束不适合纳入公约，纳入了也缺乏约束力。
