### ISSUE TITLE
[疑问] 如果应用正常工作的时候，必须依赖后台进程，也可以加入公约吗？

### ISSUE THREAD

**Issue by ksxkq** [green-android/green-android.github.io#12]
比如一些工具类应用，类似 悬浮球，正常运行的时候会一直在后台，同时也可以通过悬浮球启动第三方应用；又或者是类似锤子大爆炸这样的应用，在后台监听剪贴板或者根据用户的操作来完成一些动作。

这种应用的特点就是前台页面只是为了设置，真正运行的时候是会一直在后台，等待用户主动触发。

**Comment by oasisfeng** [comment]
后台限制的要求不适用于前台服务。但如果使用前台服务，必须提供可避免或关闭前台服务的选项。（即选择权在用户）
