### ISSUE TITLE
向网页中加入面向用户的公约说明

### ISSUE THREAD

**Issue by WordlessEcho** [green-android/green-android.github.io#13]
现有的公约说明对于普通用户仍然不够友好，我希望能有一段简洁、明确的文字告诉普通用户公约是什么，这样更加有利于提高公约知名度，使得公约更好地被推行

**Comment by oasisfeng** [comment]
已在公约首页醒目位置加入『遵循公约的应用，后台不费电、手机不卡顿，跟 iPhone 一样省心。』
