### ISSUE TITLE
[疑问]后台纯净-阿里云推送服务

### ISSUE THREAD

**Issue by twocity** [green-android/green-android.github.io#14]
对于使用了阿里云推送服务的 APP，即使应用切入后台，也会有几个 Background Service 一直在运行：

```
com.alibaba.sdk.android.push.channel.CheckService
com.taobao.accs.ChannelService
com.taobao.accs.data.MsgDistributeService
```
这几个 servcie 也无法通过正常途径停止掉（stopService），显然不符合『后台纯净』的规约。
对此有什么建议可以处理这种情况？

**Comment by oasisfeng** [comment]
无法通过stopService()停掉，具体是什么表现？Service会自己重启，还是完全没有停止？可以从系统设置的『运行中的服务』中的服务持续时长区分。

**Comment by twocity** [comment]
service 会自启

**Comment by oasisfeng** [comment]
建议试试在stopService之前PackageManager.setComponentEnabledState()禁用会自动重启的服务。
