### ISSUE TITLE
请问想要通过认证必须接入Project Condom吗？

### ISSUE THREAD

**Issue by ExenVitor** [green-android/green-android.github.io#15]
我们的应用没有接入国内第三方推送相关的SDK，仅仅有几个社交平台的分享SDK和七牛云的SDK，没有观察到会自动唤醒其它第三方应用的现象，并且我们已经默认达成【后台纯净】了。
在使用绿色守护自检时(v3.4.2)，被告知没有发现接入Project Condom，那在这种情况下我们想申请通过认证的话，需要接入Project Condom吗？

**Comment by oasisfeng** [comment]
不是必须的。自检时的提示是『如果没有接入Project Condom，需要自行确认是否存在唤醒第三方应用的现象』
