### ISSUE TITLE
[公约]草案文本格式

### ISSUE THREAD

**Issue by la3rence** [green-android/green-android.github.io#17]
格式控建议中英文、数字与中文之间加一个半角空格。（逃

> 周期性唤醒CPU会打断设备的深度睡眠状态，造成设备待机时长的明显缩短。按照Google在Project Volta中的粗略测算，设备每1秒钟的活跃工作会让待机时间损失大约2分钟。大部分应用的后台周期性任务往往以网络访问为主，通常会持续数秒至数十秒（甚至超过1分钟）。

周期性唤醒 CPU 会打断设备的深度睡眠状态，造成设备待机时长的明显缩短。按照 Google 在 Project Volta
 中的粗略测算，设备每 1 秒钟的活跃工作会让待机时间损失大约 2 分钟。大部分应用的后台周期性任务往往以网络访问为主，通常会持续数秒至数十秒（甚至超过 1 分钟）。

**Comment by WordlessEcho** [comment]
你完全可以发起一个 pull request，为什么不试试呢 : )

**Comment by oasisfeng** [comment]
我一直觉得这个功能应该由渲染引擎（或者相关的机制）解决，而不是靠人工确保，这样实在吃力不讨好……

**Comment by Leo-Mu** [comment]
Office Word 的渲染风格就是自动加空格的，不知道有没有开源 CSS 项目做这方面处理。

**Comment by drakeet** [comment]
支持，另外，已经有源码（markdown 文件）了，等新版公约发布了，咱们可以提交一个 PR 来完善这个内容。

**Comment by oasisfeng** [comment]
抱歉，目前暂不考虑接受添加空格的PR，因为这并不具备长期的可持续性。希望各位提交能自动化处理或改善渲染的Jekyll插件（不仅限于GitHub Pages的支持范围）。
