### ISSUE TITLE
应用能否获取“android.permission.READ_PHONE_STATE”权限

### ISSUE THREAD

**Issue by jackinside** [green-android/green-android.github.io#19]
我们应用的提醒功能会播放铃声，这时用户正好在通话过程中，铃声会带来很大干扰。为了监测用户是否在通话，我们需要“android.permission.READ_PHONE_STATE”权限。请问有什么方法来解决这个问题吗？

**Comment by oasisfeng** [comment]
TelephonyManager.getCallState() 和 listen() 接口，后者使用 LISTEN_CALL_STATE 并不需要上述权限。
