### ISSUE TITLE
[公约] 建议和谷歌加强沟通，由安卓系统 统一 处理应用的推送消息

### ISSUE THREAD

**Issue by digitbear** [green-android/green-android.github.io#23]
建议和谷歌加强沟通，能否针对中国区安卓系统集成一套不用gcm的推送规范。

包括：
1. 应用只能向系统注册推送服务端的地址或者链接。 不允许自行保活去查推送消息。
2. 系统定期把已经注册的各推送链接做 查询 新的推送消息。
3. 规范和定义 推送端服务端的和安卓系统交互的协议。

这种方案可以解决由系统层面去统一处理各个推送消息并进行管理，应用也就不需要进行各种保活， 可以大大增强设备体验。

**Comment by oasisfeng** [comment]
Google 没有这个意愿。
