### ISSUE TITLE
[公约]关于原生运行库相关的问题

### ISSUE THREAD

**Issue by YandexStudio** [green-android/green-android.github.io#25]
尽管并非所有情况下64位运行库都能比32位运行库在性能上有所提升，但考虑到32位设备绝大多数已被淘汰，是否应当限制，如果使用了原生运行库，则至少应包含面向arm64编译的运行库？

**Comment by oasisfeng** [comment]
与公约的定位不符，目前公约只专注于设备体验，不涉足运行性能。
