### ISSUE TITLE
[网站] HTTPS 证书

### ISSUE THREAD

**Issue by JokerQyou** [green-android/green-android.github.io#3]
网站域名 https://green-android.org 对应的证书是 LE Authority X3 颁布给 blog.beard.ink 域名的，对于一些用户造成疑惑。是否可以使用与实际显示域名一致的证书？

**Comment by oasisfeng** [comment]
网站的证书是由Firebase统一颁发的，blog.beard.ink只是这个证书的域名集中的一个（正好是第一个罢了），并不是说这个证书就是这个网站的。任何正常的浏览器都不会视这个证书存在疑惑的。
