### ISSUE TITLE
[公约]

### ISSUE THREAD

**Issue by andasl** [green-android/green-android.github.io#4]
关于建议 第一点，在Android 4.4以上设备中，避免使用『读取 / 写入外部存储』权限。
不得不标识，华为手机，荣耀7 16G 内部存储完全不够用，现在基本剩下几百M，经常卡得要命，
so，感觉还是少写在内部存储好点

**Comment by oasisfeng** [comment]
你指的是希望写入external storage，还是removable storage？公约中提到的外部存储指的是external storage，我应该注明一下英文，以免产生歧义。

**Comment by andasl** [comment]
额....我以为只有内部存储和外部存储两种……
