### ISSUE TITLE
自启动权限

### ISSUE THREAD

**Issue by hgang** [green-android/green-android.github.io#5]
作为普通应用如无必要，请不要申请开启自动启动
permission: android.permission.RECEIVE_BOOT_COMPLETED
action: android.intent.action.BOOT_COMPLETED

**Comment by YueDev** [comment]
如果有一个能正常使用的系统推送服务，很多app完全可以不需要后台或者自启动来接受自己的消息。

**Comment by oasisfeng** [comment]
[按照Android官方的解释](https://developer.android.google.cn/preview/features/background-broadcasts.html)：

> Exempted because these broadcasts are only sent only once, at first boot, and many apps need to receive this broadcast to schedule jobs, alarms, and so forth.

如果认为不必要，还望给出替代的最佳实践。
