### ISSUE TITLE
允许用户拒绝特定权限

### ISSUE THREAD

**Issue by kghost** [green-android/green-android.github.io#7]
当程序申请权限时，用户可以拒绝，程序应当关闭依赖此权限的功能，其他功能应该能够正常使用。

比如微信扫一扫依赖摄像头权限，当用户拒绝微信使用摄像头时，微信可以关闭扫一扫功能，但是其他功能必须能够正常使用。

**Comment by oasisfeng** [comment]
目前公约强调『可被验证性』这一原则，所以存在主观裁量的约束不适合纳入公约，纳入了也缺乏约束力。

比如『其他功能』的边界怎么界定？是由应用开发者解读或是？
