### ISSUE TITLE
[公约]

### ISSUE THREAD

**Issue by Chinegoodman** [green-android/green-android.github.io#9]
H5开发者表示支持i！尤其作为一个安卓机用户。。。

**Comment by Humi2011** [comment]
这需要一些主流开发公司或设备生产方引导才有可能完成；
中小开发者也许并没有看到这些相关或认为与自己无关；
总的来说这份公约需要一定数量或一定名气的开发商/个人为此背书

**Comment by oasisfeng** [comment]
此 Issue tracker 不是讨论区。
